// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojycqbeloohqvijpsbra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeWNxYmVsb29ocXZpanBzYnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mzc2MjYsImV4cCI6MjA2OTMxMzYyNn0.0GlUKVQRg6zM2vXkZlxd9MWZaO5nW_erSTt_nPvXj6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});